// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solar.Api.Persistencia;

#nullable disable

namespace Solar.Api.Persistencia.Migrations
{
    [DbContext(typeof(SolarDbContext))]
    [Migration("20260912183807_ImoveisSugeridosNaMensagem")]
    partial class ImoveisSugeridosNaMensagem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Solar.Api.Dominio.Conversa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizada_em");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Desfecho")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("desfecho");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<int>("TentativasReengajamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativas_reengajamento");

                    b.HasKey("Id")
                        .HasName("pk_conversas");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_conversas_lead_id");

                    b.ToTable("conversas");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Corretor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("ContatoInterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contato_interno");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("especialidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.PrimitiveCollection<List<string>>("Regioes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("regioes");

                    b.HasKey("Id")
                        .HasName("pk_corretores");

                    b.HasIndex("Especialidade", "Ativo")
                        .HasDatabaseName("ix_corretores_especialidade_ativo");

                    b.ToTable("corretores");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Encaminhamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversa_id");

                    b.Property<Guid?>("CorretorId")
                        .HasColumnType("uuid")
                        .HasColumnName("corretor_id");

                    b.Property<DateTimeOffset>("Em")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("em");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("especialidade");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_encaminhamentos");

                    b.HasIndex("ConversaId")
                        .IsUnique()
                        .HasDatabaseName("ix_encaminhamentos_conversa_id");

                    b.HasIndex("CorretorId")
                        .HasDatabaseName("ix_encaminhamentos_corretor_id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_encaminhamentos_lead_id");

                    b.ToTable("encaminhamentos");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset?>("ConsentimentoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consentimento_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("ExpectativaRetorno")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("expectativa_retorno");

                    b.Property<string>("Intencao")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("intencao");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int?>("PrecoMax")
                        .HasColumnType("integer")
                        .HasColumnName("preco_max");

                    b.Property<int?>("PrecoMin")
                        .HasColumnType("integer")
                        .HasColumnName("preco_min");

                    b.Property<int?>("Quartos")
                        .HasColumnType("integer")
                        .HasColumnName("quartos");

                    b.Property<string>("Regiao")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("regiao");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("novo")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Urgencia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("urgencia");

                    b.Property<string>("VersaoAvisoPrivacidade")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("versao_aviso_privacidade");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_leads_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Telefone")
                        .IsUnique()
                        .HasDatabaseName("ix_leads_telefone")
                        .HasFilter("telefone IS NOT NULL");

                    b.ToTable("leads");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Mensagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversa_id");

                    b.Property<DateTimeOffset>("Em")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("em");

                    b.Property<string>("ImoveisSugeridos")
                        .HasColumnType("jsonb")
                        .HasColumnName("imoveis_sugeridos");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("papel");

                    b.Property<string>("ProximaAcao")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("proxima_acao");

                    b.Property<long?>("SlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("slot_id");

                    b.Property<string>("StatusAgendamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_agendamento");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("texto");

                    b.HasKey("Id")
                        .HasName("pk_mensagens");

                    b.HasIndex("SlotId")
                        .HasDatabaseName("ix_mensagens_slot_id");

                    b.HasIndex("ConversaId", "Id")
                        .HasDatabaseName("ix_mensagens_conversa_id_id");

                    b.ToTable("mensagens");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Slot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CorretorId")
                        .HasColumnType("uuid")
                        .HasColumnName("corretor_id");

                    b.Property<DateTimeOffset>("Fim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim");

                    b.Property<DateTimeOffset>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.HasKey("Id")
                        .HasName("pk_slots");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_slots_lead_id");

                    b.HasIndex("CorretorId", "Inicio")
                        .IsUnique()
                        .HasDatabaseName("ix_slots_corretor_id_inicio");

                    b.ToTable("slots");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Conversa", b =>
                {
                    b.HasOne("Solar.Api.Dominio.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversas_leads_lead_id");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Encaminhamento", b =>
                {
                    b.HasOne("Solar.Api.Dominio.Conversa", null)
                        .WithMany()
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_encaminhamentos_conversas_conversa_id");

                    b.HasOne("Solar.Api.Dominio.Corretor", "Corretor")
                        .WithMany()
                        .HasForeignKey("CorretorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_encaminhamentos_corretores_corretor_id");

                    b.HasOne("Solar.Api.Dominio.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_encaminhamentos_leads_lead_id");

                    b.Navigation("Corretor");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Mensagem", b =>
                {
                    b.HasOne("Solar.Api.Dominio.Conversa", null)
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mensagens_conversas_conversa_id");

                    b.HasOne("Solar.Api.Dominio.Slot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mensagens_slots_slot_id");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Slot", b =>
                {
                    b.HasOne("Solar.Api.Dominio.Corretor", "Corretor")
                        .WithMany()
                        .HasForeignKey("CorretorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_slots_corretores_corretor_id");

                    b.HasOne("Solar.Api.Dominio.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_slots_leads_lead_id");

                    b.Navigation("Corretor");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Conversa", b =>
                {
                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
