// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Solar.Api.Persistencia;

#nullable disable

namespace Solar.Api.Persistencia.Migrations
{
    [DbContext(typeof(SolarDbContext))]
    partial class SolarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Solar.Api.Dominio.Conversa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizada_em");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.HasKey("Id")
                        .HasName("pk_conversas");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_conversas_lead_id");

                    b.ToTable("conversas");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("ExpectativaRetorno")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("expectativa_retorno");

                    b.Property<string>("Intencao")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("intencao");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int?>("PrecoMax")
                        .HasColumnType("integer")
                        .HasColumnName("preco_max");

                    b.Property<int?>("PrecoMin")
                        .HasColumnType("integer")
                        .HasColumnName("preco_min");

                    b.Property<int?>("Quartos")
                        .HasColumnType("integer")
                        .HasColumnName("quartos");

                    b.Property<string>("Regiao")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("regiao");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Urgencia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("urgencia");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.ToTable("leads");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Mensagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversa_id");

                    b.Property<DateTimeOffset>("Em")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("em");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("papel");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("texto");

                    b.HasKey("Id")
                        .HasName("pk_mensagens");

                    b.HasIndex("ConversaId", "Id")
                        .HasDatabaseName("ix_mensagens_conversa_id_id");

                    b.ToTable("mensagens");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Conversa", b =>
                {
                    b.HasOne("Solar.Api.Dominio.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversas_leads_lead_id");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Mensagem", b =>
                {
                    b.HasOne("Solar.Api.Dominio.Conversa", null)
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mensagens_conversas_conversa_id");
                });

            modelBuilder.Entity("Solar.Api.Dominio.Conversa", b =>
                {
                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
